export const GET_CLAIMS_PENDING = "GET_CLAIMS_PENDING";
export const GET_CLAIMS_SUCCESS = "GET_CLAIMS_SUCCESS";
export const GET_CLAIMS_FAILED = "GET_CLAIMS_FAILED";

export const GET_ONE_CLAIM_SUCCESS = "GET_CLAIM_SUCCESS";
export const GET_ONE_CLAIM_FAILED = "GET_CLAIM_FAILED";

export const ADD_CLAIM_PENDING = "ADD_CLAIM_PENDING";
export const ADD_CLAIM_SUCCESS = "ADD_CLAIM_SUCCESS";
export const ADD_CLAIM_FAILED = "ADD_CLAIM_FAILED";

export const DELETE_CLAIM_PENDING = "DELETE_CLAIM_PENDING";
export const DELETE_CLAIM_SUCCESS = "DELETE_CLAIM_SUCCESS";
export const DELETE_CLAIM_FAILED = "DELETE_CLAIM_FAILED";

export const EDIT_CLAIM_PENDING = "EDIT_CLAIM_PENDING";
export const EDIT_CLAIM_SUCCESS = "EDIT_CLAIM_SUCCESS";
export const EDIT_CLAIM_FAILED = "EDIT_CLAIM_FAILED";
